# SPDX-License-Identifier: Apache-2.0
#
# Application Kconfig defaults.
# See Kconfig (menu "my_app Configuration") for all app-level options.

# UART console (obtained from Devicetree chosen node)
CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y

# Logging subsystem — outputs trace over UART via LOG backend
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y

# Wi-Fi
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y

# Network stack
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y


# ADC (wymagane przez VMON_BACKEND_ADC)
CONFIG_ADC=y

CONFIG_VMON_BACKEND_ADC=n

# I2C (wymagane przez VMON_BACKEND_I2C)
CONFIG_I2C=y
CONFIG_VMON_BACKEND_I2C=y

# I2C: 2 bajty, wartość już w mV
CONFIG_VMON_I2C_READ_BYTES=2
CONFIG_VMON_I2C_SCALE_NUM=1
CONFIG_VMON_I2C_SCALE_DEN=1

# Sensor subsystem
CONFIG_SENSOR=y

# DNS (opcjonalnie — do rozwiązywania nazw)
CONFIG_DNS_RESOLVER=y

# my_app Wi-Fi log driver
CONFIG_APP_WIFI_LOG=y
CONFIG_APP_WIFI_LOG_SSID="your_wifi_ssid"
CONFIG_APP_WIFI_LOG_PSK="your_wifi_password"
CONFIG_APP_WIFI_LOG_SERVER_IP="192.168.50.162"
CONFIG_APP_WIFI_LOG_SERVER_PORT=5555